[package]
name = "sdf-test"
version = "0.1.0"
authors = ["Przemysław Lenart <przemek.lenart@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0.3"
glium = "0.22.0"
sdf = { path = "./libs/sdf" }

